//AUTH
export const UPDATE_USER = 'UPDATE_USER';

//TODOS
export const SET_TODOS = "SET_TODOS";
export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_COMPLETED_STATUS = "TOGGLE_COMPLETED_STATUS";

//HELPERS
export const TOGGLE_FULL_PAGE_LOADER = 'TOGGLE_FULL_PAGE_LOADER';