//AUTH
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_PROPERTY = 'UPDATE_USER_PROPERTY';

//TODOS
export const SET_TODOS = "SET_TODOS";
export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";

//HELPERS
export const TOGGLE_FULL_PAGE_LOADER = 'TOGGLE_FULL_PAGE_LOADER';